services:
  mysql8.0.43-debian:
    container_name: mysql8.0.43-debian
    image: mysql:8.0.43-debian
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MySqlGHdzM18*
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres16:
    container_name: postgres16
    image: postgres:16-alpine3.21
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: PostgresGHdzM18*
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc_usuarios
    image: gerardohdzm/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8.0.43-debian:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: MySqlGHdzM18*
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8.0.43-debian
    restart: always

  msvc-cursos:
    container_name: msvc_cursos
    image: gerardohdzm/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
#    env_file: ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres16:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: PostgresGHdzM18*
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - spring
    depends_on:
      - postgres16
      - msvc-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring
